# Generated by Django 6.1 on 2026-09-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0003_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='password',
            field=models.CharField(default='agent123', max_length=128),
        ),
        migrations.AddField(
            model_name='computer',
            name='username',
            field=models.CharField(default='agent', max_length=100),
        ),
    ]
