# Generated by Django 5.2.17 on 2026-10-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0003_blockedapp_alter_allowedsite_id_alter_blockedsite_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedapp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedapp',
            name='name',
            field=models.CharField(help_text='Masalan: telegram.exe', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='blockedapp',
            unique_together={('user', 'name')},
        ),
    ]
