# Generated by Django 5.2.17 on 2026-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0006_sharedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sharedaccount',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sharedaccount',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
