# Generated by Django 5.2.17 on 2026-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0009_userprofile_location_discoverability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sharedaccount',
            name='district',
        ),
        migrations.RemoveField(
            model_name='sharedaccount',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_discoverable',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.AlterField(
            model_name='allowedsite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharedaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yangi_akaunt_ochis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
