# Generated by Django 6.1.1 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0011_blockedsite_alter_allowedsite_id_alter_command_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='district',
            field=models.CharField(blank=True, help_text='Tuman', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='region',
            field=models.CharField(blank=True, help_text='Viloyat (masalan: Toshkent)', max_length=100, null=True),
        ),
    ]
