# Generated by Django 6.1.1 on 2026-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0012_computer_district_computer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedsite',
            name='domain',
            field=models.CharField(help_text='Masalan: google.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='computer_name',
            field=models.CharField(default="Noma'lum kompyuter", max_length=255),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='domain',
            field=models.CharField(help_text='Sayt domeni', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='url',
            field=models.TextField(help_text="To'liq havola"),
        ),
    ]
