# Generated by Django 6.1.1 on 2026-09-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0014_userprofile_location_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedsite',
            name='domain',
            field=models.CharField(help_text='Masalan: youtube.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='computer_name',
            field=models.CharField(default="Noma'lum kompyuter", help_text='Kompyuter nomi yoki egasi', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='domain',
            field=models.CharField(help_text='Sayt domeni (masalan: instagram.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Urinish vaqti'),
        ),
        migrations.AlterField(
            model_name='sitewarning',
            name='url',
            field=models.TextField(help_text="Foydalanuvchi kirmoqchi bo'lgan to'liq havola"),
        ),
    ]
