# Generated by Django 6.1.1 on 2026-10-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0015_alter_allowedsite_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='region',
        ),
        migrations.AddField(
            model_name='command',
            name='computer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
