# Generated by Django 6.1.1 on 2026-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rules', '0002_agentcommandroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterule',
            name='is_silent',
            field=models.BooleanField(default=False),
        ),
    ]
